#!/bin/sh

systemctl --user import-environment DISPLAY
clipmenud &

# Night mode
# LA
redshift -l 34.05223:-118.24368 -m randr &
# PA
# redshift -l 39.9535743:-75.187736 -m randr &

# Hide mouse
unclutter &
