# border_width = 1
# margin = 2
# default_border_color = "#5e81ac"
# focused_border_color = "#a3be8c"
# floating_border_color = "#88c0d0"
border_width = 1
margin = 2
default_border_color = "#458588"
floating_border_color = "#689d6a"
focused_border_color = "#b16286"
